# Generated by Django 5.2.7 on 2026-03-21 09:38

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('biography', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('hall_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'Hall',
            },
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('play_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plays')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.genre')),
            ],
            options={
                'db_table': 'Play',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('liked_plays', models.ManyToManyField(blank=True, related_name='liked_by', to='main.play')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PlayActor',
            fields=[
                ('pk', models.CompositePrimaryKey('play_id', 'actor_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actor')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.play')),
            ],
            options={
                'db_table': 'PlayActor',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(related_name='plays', through='main.PlayActor', to='main.actor'),
        ),
        migrations.CreateModel(
            name='PlayDirector',
            fields=[
                ('pk', models.CompositePrimaryKey('play_id', 'director_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.director')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.play')),
            ],
            options={
                'db_table': 'PlayDirector',
            },
        ),
        migrations.AddField(
            model_name='play',
            name='directors',
            field=models.ManyToManyField(related_name='plays', through='main.PlayDirector', to='main.director'),
        ),
        migrations.CreateModel(
            name='PlayRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.play')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'play')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rated_plays',
            field=models.ManyToManyField(related_name='ratings', through='main.PlayRating', to='main.play'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hall')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.play')),
            ],
            options={
                'db_table': 'Schedule',
                'unique_together': {('play', 'hall', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('theatre_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Theatre',
                'unique_together': {('name', 'city')},
            },
        ),
        migrations.AddField(
            model_name='hall',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.theatre'),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('theatre', 'name')},
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schedule')),
            ],
            options={
                'db_table': 'Ticket',
                'unique_together': {('schedule_id', 'seat')},
            },
        ),
    ]
